## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
# your code
np.random.seed(42)
A = np.random.randint(0, 11, size=10)

print(A)

mask = (A > 3) & (A < 8)

A[mask] = A[mask] * -1

print(A)

[ 6  3 10  7  4  6  9  2  6 10]
[-6  3 10 -7 -4 -6  9  2 -6 10]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
# your code
np.random.seed(53)
A = np.random.randint(0, 51, size=10)
print(A)

max_value = np.max(A)
print(max_value)

mask = (A == max_value)
A[mask] = 0
print(A)

[25 29 37 22 48 24 12  9  5 18]
48
[25 29 37 22  0 24 12  9  5 18]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [11]:
# your code
X = np.arange(2*3).reshape(2,-1) 
print(X)

col1 = np.repeat(X[0], len(X[1]))
col2 = np.tile(X[1], len(X[0]))

result = np.stack((col1, col2), axis=1)
print(result)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [0 4]
 [0 5]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [113]:
# your code
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

print("A:\n", A, "\nB:\n", B)

mask = []
for a in A:
    a_unique = np.unique(a)
    mask.append(all(all(np.isin(b, a_unique)) for b in B))

result = A[mask]

print("\nMask:\n", mask)
print("\nResult:\n", result)

A:
 [[0 2 1]
 [4 3 1]
 [1 2 2]
 [4 2 0]
 [4 3 0]
 [1 2 3]
 [4 2 0]
 [1 1 2]] 
B:
 [[4 4]
 [2 2]]

Mask:
 [False, False, False, True, False, False, True, False]

Result:
 [[4 2 0]
 [4 2 0]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [109]:
# your code
A = np.random.randint(0, 5, (10, 3))

mask = A.max(axis=1) != A.min(axis=1)
result = A[mask]

print(f"Result: \n{result}")
print(f"Resault shape: \n{result.shape}")
print(f"Origin shape: \n{A.shape}")

Result: 
[[0 3 1]
 [3 0 3]
 [3 1 1]
 [0 3 2]
 [3 0 2]
 [3 1 0]
 [3 1 0]
 [2 2 0]
 [1 2 0]
 [3 0 0]]
Resault shape: 
(10, 3)
Origin shape: 
(10, 3)


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [114]:
# your code
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

A_unique = np.unique(A, axis=0)

print(A_unique)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [117]:
# your code
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X_list = list(X)

# Python
diag_len = min(len(X_list), len(X_list[0]))
prod = 1
for i in range(diag_len):
    if X_list[i][i] != 0:
        prod *= X[i][i]

print(prod)

# NumPy
diag = np.diagonal(X)
diag_nonzero = diag[diag != 0]
prod = np.prod(diag_nonzero)

print(prod)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [119]:
# your code
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x_list = list(x)
y_list = list(y)

# Python
same_multiset = sorted(x_list) == sorted(y_list)
print(same_multiset)

# NumPy
same_multiset = np.array_equal(np.sort(x), np.sort(y))
print(same_multiset)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [123]:
# your code
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x_list = list(x)

# Python
candidates = (x_list[i] for i in range(1, len(x_list)) if x_list[i-1] == 0)
max_value = max(candidates)
print(max_value)

# NumPy
mask = x[:-1] == 0
max_value = np.max(x[1:][mask])
print(max_value)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [136]:
# your code
x = np.array([2, 2, 2, 3, 3, 3, 5])
x_list = [2, 2, 2, 3, 3, 3, 5]

# Python
values = []
counts = []
current = x_list[0]
count = 1

for elem in x_list[1:]:
    if elem == current:
        count += 1
    else:
        values.append(current)
        counts.append(count)
        current = elem
        count = 1
values.append(current)
counts.append(count)

tup = (values, counts)
print(tup)

# NumPy
diff = np.diff(x) != 0
full_diff = np.append(diff, True)
indices = np.where(full_diff)[0]

counts = np.diff(np.append(-1, indices))
values = x[indices]

tup = (values, counts)
print(tup)


([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [139]:
%%time
# your code

# Python
import math

X = [[1, 2], [3, 4], [5, 6]]
Y = [[0, 0], [1, 1]]

dist_matrix = []

for x in X:
    row = []
    for y in Y:
        d = math.sqrt(sum((xi - yi)**2 for xi, yi in zip(x, y)))
        row.append(d)
    dist_matrix.append(row)

print(dist_matrix)

[[2.23606797749979, 1.0], [5.0, 3.605551275463989], [7.810249675906654, 6.4031242374328485]]
CPU times: total: 0 ns
Wall time: 1 ms


In [140]:
%%time

# NumPy
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[0, 0], [1, 1]])

X_sq = np.sum(X**2, axis=1).reshape(-1, 1)
Y_sq = np.sum(Y**2, axis=1).reshape(1, -1)
dist_matrix = np.sqrt(X_sq + Y_sq - 2 * X @ Y.T)

print(dist_matrix)

[[2.23606798 1.        ]
 [5.         3.60555128]
 [7.81024968 6.40312424]]
CPU times: total: 0 ns
Wall time: 998 μs


In [141]:
%%time

# SciPy
from scipy.spatial.distance import cdist

dist_matrix = cdist(X, Y, metric='euclidean')
print(dist_matrix)

[[2.23606798 1.        ]
 [5.         3.60555128]
 [7.81024968 6.40312424]]
CPU times: total: 0 ns
Wall time: 1e+03 μs


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [142]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [143]:
# your code
average_calories = np.mean(calorie_stats) - 60
print(average_calories)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [144]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [145]:
# your code
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [148]:
# your code
percentiles = np.percentile(calorie_stats, np.arange(0, 101))
nth_percentile = np.min(np.where(percentiles > 60))
print(nth_percentile)

4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [149]:
# your code
more_calories = np.mean(calorie_stats > 60)
print(more_calories)

0.961038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
# your code
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


In [154]:
print(
"""
Среднее отклонение равно 19.35, а среднее значение 106.88 калорий, 
значит большинство брендов находятся в диапазоне ~85-125 калорий, что все равно значительно больше, 
чем значения калорий наших CrunchieMunchies (60 калорий)
"""
)


Среднее отклонение равно 19.35, а среднее значение 106.88 калорий, 
значит большинство брендов находятся в диапазоне ~85-125 калорий, что все равно значительно больше, 
чем значения калорий наших CrunchieMunchies (60 калорий)



8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [156]:
# your code
print(
"""
Анализ данных о калорийности показал, что: 
    1. Значения калорийности нашего продукта CrunchieMunchies равно 60 каориям;
    2. Конкурирующие бренды содержат в среднем на 47 калорий больше, чем наши CrunchieMunchies; 
    3. Медиана калорийности равна 110 калориям, что почти вдвое превышает нашу норму; 
    4. Более 96% хлопьев на рынке имеют более 60 калорий на порцию; 
    5. Стандартное отклонение у конкурентов равно 19 калорий. 
Это доказательство того, что большинство брендов стабильно остаются в диапазоне высоких значений. 
А это, в свою очередь, существенно выделяет CrunchieMunchies среди конкурентов как более здоровый и низкокалорийный продукт.
При маркетинговых компаниях есть смысл акцентировать на этом внимание: CrunchieMunchies - один из самых низкокалорийных завтраков на рынке.
"""
)


Анализ данных о калорийности показал, что: 
    1. Значения калорийности нашего продукта CrunchieMunchies равно 60 каориям;
    2. Конкурирующие бренды содержат в среднем на 47 калорий больше, чем наши CrunchieMunchies; 
    3. Медиана калорийности равна 110 калориям, что почти вдвое превышает нашу норму; 
    4. Более 96% хлопьев на рынке имеют более 60 калорий на порцию; 
    5. Стандартное отклонение у конкурентов равно 19 калорий. 
Это доказательство того, что большинство брендов стабильно остаются в диапазоне высоких значений. 
А это, в свою очередь, существенно выделяет CrunchieMunchies среди конкурентов как более здоровый и низкокалорийный продукт.
При маркетинговых компаниях есть смысл акцентировать на этом внимание: CrunchieMunchies - один из самых низкокалорийных завтраков на рынке.

